config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, path_prefix: 'd'
  resources :users, except: [:show, :destroy] do
    put 'status', on: :member
    put 'roles', on: :member
  end
  root to: 'home#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  validates :user_name, presence: true, uniqueness: {
    :case_sensitive => false
  }
  attr_accessor :login

  before_create :assign_role

  #scope :include_user_roles, include: [:roles]

  scope :include_user_roles, -> {
    includes("roles")
  }

  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  def user_roles
    #return self.roles.first.name.capitalize
    #return self.roles.collect(&:name).join(", ")
    return roles.collect{|role| role.name.capitalize}.join(", ")
  end
  
  def active_for_authentication?
    # Comment out the below debug statement to view the properties of the returned self model values.
    # logger.debug self.to_yaml
    super && active?
  end

  private

  def assign_role
    self.role_ids = Role.where(name: 'chemist').first.id
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:login, :user_name,:current_password, :email, :password, :remember_me, :role_ids) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!#, :authorize_role

  def index
    @roles = Role.all
    users = User.include_user_roles
    #    @users = (params[:search] ?
    #        users.search(params[:search], include: [:roles], star: true) :
    #        users).paginate(page: params[:page], per_page: 10)
    @users = users.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      #format.xls { send_data @users.to_xls, content_type: 'application/vnd.ms-excel', filename: 'users.xls' }
    end
  end

#  def update
#    @user = User.find(params[:id])
#    #raise params[:user].inspect
#    successfully_updated = if !params[:user][:password].blank?
#      @user.update_attributes!(user_params)
#    else
#      @user.update_without_password(user_params)
#    end
#    respond_to do |format|
#      if successfully_updated
#        format.html { redirect_to users_path, notice: "User was successfully updated."}
#        format.json { head :no_content }
#      else
#        format.html { render "edit" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  def status
    user = User.find(params[:id])
    user.update_attribute('active', !user.active)
    render nothing: true
  end

  def roles
    #raise params.inspect
    user = User.find(params[:id])
    user.roles.each do |role|
      role.destroy
    end
    #params[:user][:role_ids].each do |role_id|
      user.roles.create(params[:user]) #unless role_id == ""
    #end
    respond_to do |format|
        format.html { redirect_to users_path, notice: "User was successfully updated."}
        format.json { head :no_content }
     end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :user_name,:current_password, :email, :password, :remember_me, :role_ids)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_common_links(hash)
    html = ""
    #html += link_to('Export To Excel', hash[:index_path]) + " | " if hash[:object].present?
    html += link_to(hash[:create_text], hash[:create_path])
    return html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_user_widget.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Claims</a>-->
      <%= link_to "Claims", root_path ,class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Users', users_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <% end %>
        </ul>
        <!--<form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>-->
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.user_name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Update Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <!--<li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>-->
              </ul>
            </li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User Space <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Login', new_user_session_path %></li>
                <li><%= link_to 'Signup', new_user_registration_path %></li>
                <!--<li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>-->
              </ul>
            </li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClaimsNew</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/user_widget' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </p>
      <% end %>
      <%= yield %>
  
    </div>
  </body>
  </html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal fade" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= simple_form_for user, url: roles_user_path(user), html: {method: :put, class: 'form-horizontal' } do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Change Role</h4>
          </div>

          <div class="modal-body">
            <p>
              <%= f.input :role_ids, collection: roles, as: :check_boxes, label_method: lambda {|t| t.name.titleize}, label: false %>
            </p>
          </div>
          <div class="modal-footer">
    <%#= f.submit "Change Role", class: "btn-primary" %>
            <button type="submit" class="btn btn-primary">Change Role</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/_users.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Active</th>
      <th data-sorter="false">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td width="10%"><%= user.user_name %></td>
        <td width="30%"><%= user.email %></td>
        <td width="20%"><%= user.user_roles %></td>
        <td width="20%">
          <% if current_user != user %>
            <p class="switch" id="<%= user.id %>">
              <label class="cb-enable <%= 'selected' if user.active? %>"><span>Yes</span></label>
              <label class="cb-disable <%= 'selected' if !user.active? %>"><span>No</span></label>
            </p>
          <% else %>
            Yes
          <% end %>
        </td>
        <td width="20%">
          <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-min' %>
            <% if current_user != user %>
              <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn" type="button">Change role</a>
              <%= render user, roles: roles %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="5"><%= pluralize(users.size, 'user') %></td>
      </tr>
    </tfoot>
  </table>

app/views/users/index.html.erb
<div align="right">
  <%= generate_common_links({index_path: users_path(request.parameters.merge({format: :xls})), create_path: new_user_path, object: @users, create_text: "Add New User" }) %>
</div>
<div align="left">
<%#= generate_search_form({index_path: users_path, placeholder: params[:search] ? params[:search] : "Search Users" }) %>
</div>
<fieldset>
  <legend> Users List</legend>
  <%= render "users", users: @users, roles: @roles %>
  <%= will_paginate @users %>
</fieldset>